[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "A Nix parser written in Rust"
license-file = "LICENSE"
name = "rnix"
readme = "README.md"
repository = "https://gitlab.com/jD91mZM2/rnix"
version = "0.5.0"

[dependencies]
failure = "0.1.2"
rowan = { git = "https://github.com/matklad/rowan" }

[dev-dependencies]
criterion = "0.2.5"

[[bench]]
name = "all-packages"
harness = false
