cargo-features = ["edition"]

[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "A Nix parser written in Rust"
edition = "2018"
license-file = "LICENSE"
name = "rnix"
readme = "README.md"
repository = "https://gitlab.com/jD91mZM2/rnix"
version = "0.4.0"

[dependencies]
arenatree = "0.1.0"
failure = "0.1.2"

smol_str = { version = "0.1.2", optional = true }

[features]
default = ["smol_str"]
